
export const SINGLETON_RECIPE_REQUEST="SINGLETON_RECIPE_REQUEST";
export const SINGLETON_RECIPE_SUCCESS="SINGLETON_RECIPE_SUCCESS";
export const SINGLETON_RECIPE_FAIL="SINGLETON_RECIPE_FAIL";
export const SEARCH_RESULTS_NOT_FOUND="SEARCH_RESULTS_NOT_FOUND";
export const SEARCH_RESULTS_FOUND="SEARCH_RESULTS_FOUND";

