import { SIGN_SUCCESS,SIGN_REQUEST,AUTH_ERROR, AUTH_REQUEST, AUTH_SUCCESS, LOGIN_FAILURE, LOGIN_REQUEST, LOGIN_SUCCESS, LOGOUT_FAILURE, LOGOUT_REQUEST } from "./actionTypes"


export const sign=(formdata)=>(dispatch)=>{
dispatch({type:SIGN_REQUEST});

}