
export const SINGLETON_RECIPE_REQUEST="SINGLETON_RECIPE_REQUEST";
export const SINGLETON_RECIPE_SUCCESS="SINGLETON_RECIPE_SUCCESS";
export const SINGLETON_RECIPE_FAIL="SINGLETON_RECIPE_FAIL";
export const SEARCH_RESULTS_NOT_FOUND="SEARCH_RESULTS_NOT_FOUND";
export const SEARCH_RESULTS_FOUND="SEARCH_RESULTS_FOUND";
export const DELETE_ERROR="DELETE_ERROR";
export const DELETE_SUCESS="DELETE_SUCESS";
export const DELETE_REQUEST="DELETE_REQUEST";
export const GET_RECIPE_SUCCESS="GET_RECIPE_SUCCESS";
